import "@/styles/globals.css";
import { useState } from "react";
import type { AppProps } from "next/app";
import Head from "next/head";
import Router from "next/router";
import Loader from "@/components/Loader";
import NProgress from "nprogress";
import "nprogress/nprogress.css";

export default function App({ Component, pageProps }: AppProps) {
  const [loading, setLoading] = useState(false);

  Router.events.on("routeChangeStart", () => {
    NProgress.start();
    setLoading(true);
  });
  Router.events.on("routeChangeComplete", () => {
    NProgress.done();
    setLoading(false);
  });
  Router.events.on("routeChangeError", () => {
    NProgress.done();
    setLoading(false);
  });
  return (
    <>
      <Head>
        <title>Chainlords</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading ? <Loader /> : <Component {...pageProps} />}
    </>
  );
}
